version: "3"
services:
  api:
    build: .
    ports:
      - 3000:8080
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: restapi
      MYSQL_DATABASE: golang_restful_api
      MYSQL_USER: restapi
      MYSQL_PASSWORD: restapi
    volumes:
      - db_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db_data:
