// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-playground/validator/v10"
	"github.com/google/wire"
	"net/http"
	"restful_api/app"
	"restful_api/controller"
	"restful_api/middleware"
	"restful_api/repository"
	"restful_api/service"
)

import (
	_ "github.com/go-sql-driver/mysql"
)

// Injectors from injector.go:

func InitializeServer() *http.Server {
	productRepositoryImpl := repository.NewProductRepository()
	db := app.NewDB()
	validate := validator.New()
	productServiceImpl := service.NewProductService(productRepositoryImpl, db, validate)
	productControllerImpl := controller.NewProductController(productServiceImpl)
	router := app.NewRouter(productControllerImpl)
	authMiddleware := middleware.NewAuthMiddleware(router)
	server := NewServer(authMiddleware)
	return server
}

// injector.go:

var productSet = wire.NewSet(repository.NewProductRepository, wire.Bind(new(repository.ProductRepository), new(*repository.ProductRepositoryImpl)), service.NewProductService, wire.Bind(new(service.ProductService), new(*service.ProductServiceImpl)), controller.NewProductController, wire.Bind(new(controller.ProductController), new(*controller.ProductControllerImpl)))
